/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yjy_edu_enterprise_advanced_jni_JniClass */

#ifndef _Included_com_yjy_edu_enterprise_advanced_jni_JniClass
#define _Included_com_yjy_edu_enterprise_advanced_jni_JniClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yjy_edu_enterprise_advanced_jni_JniClass
 * Method:    speak
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yjy_edu_enterprise_advanced_jni_JniClass_speak
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yjy_edu_enterprise_advanced_jni_JniClass
 * Method:    say
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_yjy_edu_enterprise_advanced_jni_JniClass_say
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
